version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    pull-request-branch-name:
      separator: "-"
