kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: geocode
  labels:
    app.kubernetes.io/name: geocode
spec:
  parentRefs:
  - kind: Gateway
    name: external-gw
    namespace: gateway-ingress
    sectionName: https
  rules:
  - matches:
    - path:
        value: /geocode
    backendRefs:
    - name: geocode
      port: 8080