apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./base

images:
- name: geocode
  newName: ghcr.io/saidsef/faas-reverse-geocoding
  newTag: "2023.12"

commonAnnotations:
  app.kubernetes.io/part-of: geocode
