---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml
- ingress.yml

images:
- name: geocode
  newName: ghcr.io/saidsef/faas-reverse-geocoding
  newTag: latest

commonAnnotations:
  app.kubernetes.io/name: geocode
  app.kubernetes.io/part-of: geocode

vars:
- fieldref:
    fieldpath: metadata.name
  name: HOST
  objref:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: geocode
