---
apiVersion: v1
kind: Service
metadata:
  name: geocode
  labels:
    name: geocode
    app: geocode
spec:
  type: ClusterIP
  selector:
    app: geocode
  ports:
    - name: tcp-term
      protocol: TCP
      port: 8080
