---
apiVersion: v1
kind: Service
metadata:
  name: geocode
  labels:
    name: geocode
    app: geocode
  annotations:
    prometheus.io/scrape: "true"
    filter.by.port.name: "true"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
  selector:
    app: geocode
  ports:
    - name: tcp-term
      protocol: TCP
      port: 8080
