---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocode
  labels:
    app.kubernetes.io/name: geocode
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: geocode
  template:
    metadata:
      labels:
        app.kubernetes.io/name: geocode
    spec:
      hostNetwork: false
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
      - name: geocode
        image: ghcr.io/saidsef/faas-reverse-geocoding:v2022.12
        imagePullPolicy: Always
        env:
          - name: "PORT"
            value: "8080"
        securityContext:
          runAsNonRoot: true
          runAsGroup: 65534
          runAsUser: 65534
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        resources:
          requests:
           memory: "50Mi"
           cpu: "20m"
          limits:
            memory: "100Mi"
            cpu: "40m"
        livenessProbe:
          exec:
            command:
              - pgrep
              - geocode
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
