apiVersion: v2
name: reverse-geocoding
description: GeoCode Helm chart for Kubernetes
type: application
version: 0.2.1
appVersion: "0.2.1"
apiVersion: "1.21"
keywords:
  - reverse-geocoding
  - geocoding
  - kubernetes
maintainers:
  - name: Said Sef
    email: saidsef@gamil.com
    url: https://saidsef.co.uk/
