replicaCount: 1

image:
  repository: ghcr.io/saidsef/faas-reverse-geocoding
  pullPolicy: IfNotPresent
  tag: "v2024.02"

imagePullSecrets: []
nameOverride: "geocode"
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "geocode"

podAnnotations:
  prometheus.io/scrape: "true"
  filter.by.port.name: "true"

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsGroup: 65534
  runAsUser: 65534
  allowPrivilegeEscalation: false
  privileged: false
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations:
    app.kubernetes.io/name: "geocode"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: geocode.local
      paths:
        - path: /
          pathType: Prefix
  # tls: []
  #  - secretName: example-tls
  #    hosts:
  #      - example.local

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
